language: node_js
node_js:
  - "6"

branches:
  only:
  - master

before_script:
  - npm install gulp
  - npm install gulp-eslint
  
script: gulp lint
    
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
        - yungez@microsoft.com
        - zhijzhao@microsoft.com
        - kevinzha@microsoft.com
        - yaozheng@microsoft.com
        - yaweiw@microsoft.com
        - yuwzho@microsoft.com
        - reyang@microsoft.com
        - zikalino@microsoft.com
        - donzh@microsoft.com
  
matrix:
  fast_finish: true